name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Unzip unciv file
        run: |
           tar -xf files\Unciv-Windows64.zip -C files
           del files\Unciv-Windows64.zip
           dir files
        
      - name: Install WiX
        run: dotnet tool install --global wix
        
      - name: Build WiX on Windows
        run: | # Trying to set env variables for a simple command is like ???, now I truly understand the "Windows Sucks" mentality
          cmd /C "set UNCIV_VERSION=4.12.14 && wix build .\unciv.wxs"
          dir
        
      - name: Add generated binaries to artifact
        uses: actions/upload-artifact@v4
        with:
          name: Unciv-MSI
          path: |
            Unciv.msi
          if-no-files-found: error

